### ISSUE TITLE
RuntimeError: CUDA Error: out of memory

### ISSUE THREAD

**Issue by pharouknucleus** [arnoweng/CheXNet#27]
Please help me resolve this issue

**Comment by saadmanrafat** [comment]
try smaller batch size

**Comment by pharouknucleus** [comment]
I have 64 batches. and the input size is 256 and the output size 242. By how much I am going to reduce it?

**Comment by saadmanrafat** [comment]
try batch size 8, 16, 32. See if it works

**Comment by pharouknucleus** [comment]
It is still showing me this error:
Traceback (most recent call last):
  File "C:\Users\Nasir Isa\Documents\1Research\algortihm\CheXNet-master\CheXNet-master\m3.py", line 149, in <module>
    main()
  File "C:\Users\Nasir Isa\Documents\1Research\algortihm\CheXNet-master\CheXNet-master\m3.py", line 95, in main
    output = model(input_var)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\parallel\data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Nasir Isa\Documents\1Research\algortihm\CheXNet-master\CheXNet-master\m3.py", line 144, in forward
    x = self.densenet121(x)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\models\densenet.py", line 220, in forward
    features = self.features(x)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Nasir Isa\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by robhyb19** [comment]
@omrfrkmfy Were you ever able to figure out a solution to the problem? I'm dealing with the same issue

**Comment by pharouknucleus** [comment]
The issue is that your graphics card memory is small. you need to find one
with with big memory.

**Comment by Viswanath660** [comment]
With 4 worker cores of NVIDIA P100, I had to gave 12 batch size. But, the AUROC is 49%, may be due to small batch size

**Comment by cherrymj** [comment]
Maybe you can try this idea
https://blog.csdn.net/xijuezhu8128/article/details/86594478

**Comment by LiJiaqi96** [comment]
I have encountered the same issue and solved it by forcing no gradient when using model.eval()
`with torch.no_grad():`
`        for i, (data,label) in enumerate(test_loader):`
`        ...`
(Remember to use tab)
This makes the model do not save intermediate results so that temporary memory use will be freed after each batch.
May it helps.

**Comment by Candyeeee** [comment]
> With 4 worker cores of NVIDIA P100, I had to gave 12 batch size. But, the AUROC is 49%, may be due to small batch size

I am dealing with the same issue and when I try multiple times it achieves different results. Did you solve it or find why?

**Comment by icekang** [comment]
Hello, I know this is so late and it seems like the owner does not continue maintain the code for years. Yet if some of you end up with this problem and somehow, run into this issue. Try [my solution: https://github.com/arnoweng/CheXNet/pull/39](https://github.com/arnoweng/CheXNet/pull/39). I just started learning ``pytorch`` today and I'm not a pytorch pro. It is possible that my changes would lead to logic flaws. If that the case please tell me :)
